### ISSUE TITLE
不知道卡在啥地方了 反正最后结果就是Action超时了

### ISSUE THREAD

**Issue by GamerNoTitle** [aquamarine5/GenshinBirthdayReceiver#10]
![image](https://user-images.githubusercontent.com/28426291/174434013-29b78ed7-8590-441d-9a22-eb206ab941f5.png)

**Comment by GamerNoTitle** [comment]
只有今天出现了这种情况，可以暂时先观望一下

**Comment by aquamarine5** [comment]
没遇到过 期末考完再看看 没准+timeout会有用
