### ISSUE TITLE
关于COOKIE获取、一个米游社账号绑定多个原神账号的未登录问题解决办法

### ISSUE THREAD

**Issue by kmzs123** [aquamarine5/GenshinBirthdayReceiver#17]
其实网页版的COOKIE还是可以用的，只是现在米游社改了[新域名](https://www.miyoushe.com/ys/)，而且手机版可能有特殊的加密，我抓包出来的是乱码的。
如果绑定了多个原神账号，把genshin_birthday_receiver.py这个文件的第19行改成`uid = "原神uid"`
如果用网页版的COOKIE还是提示未登录就登录[米哈游通行证](https://user.mihoyo.com/)重新抓包。
另外，对于b服，我暂时没成功过，一直提示未登录，不知道为什么。

**Comment by aquamarine5** [comment]
刚才试了一下，新域名miyoushe.com的cookie确实可以（关于VMOS的README算是白写了）
手机版抓包需要在Root的虚拟机里，不root应该是无法解密的
b服这个是不是需要关联米哈游通行证？手上的确没有b服号

**Comment by kmzs123** [comment]
> 刚才试了一下，新域名miyoushe.com的cookie确实可以（关于VMOS的README算是白写了） 手机版抓包需要在Root的虚拟机里，不root应该是无法解密的 b服这个是不是需要关联米哈游通行证？手上的确没有b服号

手机版应该是有应用内的证书的，我抓包的结果是可解密部分无关紧要API，比如主页上面那一排的图标的列表，但是也依旧有无法解密的。
我的B服账号已经关联了米游社，手动打开留影叙佳期也能看到B服账号，但是手动改成B服UID就会报未登录错误

**Comment by aquamarine5** [comment]
我想我可能知道原因了，我这里所有关于badge_region都是设置的cn_gf01，是不是b服和官服这个字段不一样？

**Comment by aquamarine5** [comment]
game_biz可能也有关系，我设置的是hk4e_cn，这个可能跟国服外服有关联

**Comment by aquamarine5** [comment]
game_biz应该是游戏，我这有俩值一个是bh3_cn（崩崩崩）一个是hk4e_cn（原神）
region应该就是区服了，我这崩三就是一个pc01（全平台）一个是android01（安卓服）

**Comment by aquamarine5** [comment]
我刚才merge了更新，现在b服（前提是绑定了米哈游通行证）应该就可以领取了
