### ISSUE TITLE
去Setting/Secrets添加COOKIE secrets

### ISSUE THREAD

**Issue by liuzj288** [aquamarine5/GenshinBirthdayReceiver#6]
这一步具体哪里添加，

**Comment by aquamarine5** [comment]
![image.png](https://s2.loli.net/2022/05/26/sjyL8KJSldBCgxr.png)  
感谢提醒，在编辑图床的时候不小心把这张删了，已重新上传

**Comment by aquamarine5** [comment]
<summary>👀 >> 查看更加详细的教程 <<</summary>
  
  
### 1. 点击右上角的 Fork 按钮
- 等待刷新并自动跳转至新页面
  
### 2. 前往 [Mihoyo 米游社](https://bbs.mihoyo.com/ys) 获取Cookie
- 按`F12`，打开`开发者工具`，找到`Network`并点击
- 按`F5`刷新页面，按下图复制`Cookie`

![cookie](https://i.loli.net/2020/10/28/TMKC6lsnk4w5A8i.png)
### 3.添加Secrets
- 回到自己Fork的Github页面，依次点击`Settings`->`Secrets`->`Actions`->`New repository secret`
- 添加一个名为***COOKIE***（必须全大写）的Secrets，内容为刚才复制的Cookies
- 再添加一个名为***UID***的Secrets，内容为原神用户Uid

![image.png](https://s2.loli.net/2022/05/26/sjyL8KJSldBCgxr.png)
### 4.再次点击上方的Action
- 点击绿色按钮  ***I understand my workflows, go ahead and enable them***
![1649506736.png](https://s2.loli.net/2022/04/09/ZapToF4lhjEIKxu.png)  
- 点击左侧的GenshinBirthdayScheduleTasks
- 在 *This workflow has a workflow_dispatch event trigger.* 右侧点击**Run workflow**，branch默认为`main`即可
![image.png](https://s2.loli.net/2022/04/09/PvIwmryp7YQZsn1.png)
- 至此 部署完毕。

**Comment by aquamarine5** [comment]
## 故障排除：
- Actions运行出现红叉叉时，点击左侧的`Jobs`->`build`
- 然后打开`Run GenshinBirthdayReceiver`页
  
![image.png](https://s2.loli.net/2022/05/29/LpMuSH8aEtC35ew.png)
  
### 遇到了`'message': '当前暂未登录，请登录后重试(-100)'`，怎么办？
- 请确认在Secrets正确设置了COOKIE，见[此页面](https://github.com/aquamarine5/GenshinBirthdayReceiver#3%E6%B7%BB%E5%8A%A0secrets)

**Comment by aquamarine5** [comment]
1. 时间较长未回复
2. 代码多次更新，添加Cookie的方法可能不再可用，README的步骤应该足够详细
