### ISSUE TITLE
无法正常使用

### ISSUE THREAD

**Issue by kyomeki** [aquamarine5/GenshinBirthdayReceiver#8]
https://github.com/kyomeki/GenshinBirthdayReceiver/runs/6642066589

已经根据教程配置了正确的cookies和uid
![image](https://user-images.githubusercontent.com/103580076/170858933-fb1e158b-4f03-45a3-b9f8-abf20c1ac100.png)

**Comment by aquamarine5** [comment]
您好，请问在Secrets里面设置的名称是不是为COOKIE呢？如果是COOKIES或者Cookie都是不正确的，只有COOKIE是正确的

**Comment by aquamarine5** [comment]
刚才我提交了一个新的代码，您可以通过创建Pull Request来拉取更改，主要是为了测试有没有正确的设置COOKIE的，如果设置正确，那么在`Run GenshinBirthdayReceiver`
的
> 2022-05-29 08:55:44,740 - genshin_birthday_receiver.py[line:23] - INFO:   

下一行应该是两行 `***` 才对，否则就是Secret的设置问题，您也可以在Setting/Secrets页面截图发一下，正常的应该是这样的：
![image.png](https://s2.loli.net/2022/05/26/sjyL8KJSldBCgxr.png)  

> 如图，Repository Secrets 里面只有COOKIE和UID也只能有这两项。

Action运行见[此](https://github.com/aquamarine5/GenshinBirthdayReceiver/runs/6642252569)。

**Comment by kyomeki** [comment]
https://github.com/kyomeki/GenshinBirthdayReceiver/runs/6642696090?check_suite_focus=true#step:5:13
![S20529-18272401](https://user-images.githubusercontent.com/103580076/170863496-18ac11da-8f06-460d-bcf0-42f3f66eb4a4.png)

我同步了最新的代码后运行还是这样 Repository Secrets设置正确

**Comment by aquamarine5** [comment]
您在打开米游社获取Cookie的时候，是不是账号还没登录的状态？

**Comment by aquamarine5** [comment]
然后还有一点是，在设置Cookie的Secrets的时候，开头不需要`Cookie: `这些，按照您一开始给的截图，从`UM_dis`...到`_gat=1`才是Cookie的值的部分

**Comment by kyomeki** [comment]
> 您在打开米游社获取Cookie的时候，是不是账号还没登录的状态？

是登录后获取的cookie。根据README来的 很奇怪🤔

**Comment by kyomeki** [comment]
> 然后还有一点是，在设置Cookie的Secrets的时候，开头不需要`Cookie: `这些，按照您一开始给的截图，从`UM_dis`...到`_gat=1`才是Cookie的值的部分

对的 复制的是cookie value

**Comment by aquamarine5** [comment]
能不能加一下qq 3168287806 发一下cookie内容呢？感谢对本项目的支持

**Comment by aquamarine5** [comment]
确实想不到哪里有bug了qaq
